apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-job
spec:
  completions: 50
  parallelism: 50
  completionMode: Indexed
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: nautilus.io/sdsuinstruction
                  operator: Exists
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/sdsu-fix
        operator: Exists
      restartPolicy: Never
      initContainers:
      - name: git-clone
        image: bitnami/git:latest
        command: ["/bin/bash", "-c", "cd /src && git clone https://github.com/SDSU-Research-CI/fastchat-load-testing.git"]
        volumeMounts:
        - mountPath: /src
          name: code
      containers:
      - name: worker
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:v1.3
        command: ["python", "/src/fastchat-load-testing/fastchat-api-load-testing.py"]
        # command: ["sleep", "3600"]
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /src
          name: code
      volumes:
      - name: secret-volume
        secret:
          secretName: fastchat-api
      - name: code
        emptyDir: {}
